In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a=np.array([1,2,3,4,5])

In [10]:
a[3]=10

In [11]:
a

array([ 1,  2,  3, 10,  5])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
n[0,1]=20

In [20]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [21]:
n[:,2]

array([3, 6, 9])

In [25]:
np.random.seed(2)
np.random.rand(5,2)


array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [27]:
a=np.arange(5)

In [30]:
a=10 + a*2

In [31]:
a>=15

array([False, False, False,  True,  True])

In [32]:
a.mean()

np.float64(14.0)

In [33]:
a.std()

np.float64(2.8284271247461903)

In [3]:
u=np.array([2,4,5,6])
v=np.array([1,0,3,4])

In [4]:
def vector_multiplication(u,v):
    assert u.shape[0]==v.shape[0]
    n=u.shape[0]
    result=0.0
    for i in range(n):
        result=result+u[i]*v[i]
    return result

In [8]:
vector_multiplication(u,v)
U=np.array([[1,2,3,5],[4,5,6,8],[7,8,9,10]])

In [6]:
def matrix_vector_multiplication(m,v):
    assert m.shape[1]==v.shape[0]
    n_row=m.shape[0]
    result=np.zeros(n_row)
    for i in range(n_row):
            result[i]=vector_multiplication(m[i],v)
    return result

In [10]:
matrix_vector_multiplication(U,v)

array([30., 54., 74.])

In [16]:
U.dot(v)
V=np.array([[1,1,2],[0,1,0],[3,0,1],[4,2,1]])

In [ ]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1]==V.shape[0]
    n_row=U.shape[0]
    n_col=V.shape[1]
    result=np.zeros((n_row,n_col))
    for i in range(n_row):
        vi=V[:,i]
        result[:,i]=matrix_vector_multiplication(U,vi)
    return result

In [21]:
matrix_matrix_multiplication(U,V)

NameError: name 'j' is not defined